#version 460 core

layout(local_size_x = 64) in;

struct Chunk {
    ivec3 position;
    uint lod;
    uint indexCount;
    uint firstIndex;
    uint baseVertex;
};

struct DrawCommand {
    uint count;
    uint instanceCount;
    uint firstIndex;
    int baseVertex;
    uint baseInstance;
};

layout(std430, binding = 0) readonly buffer Chunks {
    Chunk chunks[];
};

layout(std430, binding = 1) writeonly buffer DrawCommands {
    DrawCommand commands[];
};

uniform uint chunkCount;

void main() {
    uint id = gl_GlobalInvocationID.x;

    if (id >= chunkCount)
    return;

    Chunk chunk = chunks[id];

    commands[id].count = chunk.indexCount;
    commands[id].instanceCount = 1;
    commands[id].firstIndex = chunk.firstIndex;
    commands[id].baseVertex = int(chunk.baseVertex);
    commands[id].baseInstance = id;
}