package omnivoxel.util.config;

import omnivoxel.client.game.settings.ConstantGameSettings;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

public class ConfigFile {
    private final String configName;

    public ConfigFile(String configName) {
        this.configName = configName;
    }

    private Path getConfigPath() {
        return Path.of(configName);
    }

    public Map<String, Object> load() {
        Path path = getConfigPath();
        Map<String, Object> result = new HashMap<>();

        if (!Files.exists(path)) {
            return result;
        }

        try (InputStream in = Files.newInputStream(path)) {
            Properties props = new Properties();
            props.load(in);
            for (String key : props.stringPropertyNames()) {
                result.put(key, props.getProperty(key));
            }
        } catch (IOException e) {
            System.err.println("Failed to load config '" + configName + "': " + e.getMessage());
        }

        return result;
    }

    public void write(Map<String, ?> properties) throws IOException {
        Files.createDirectories(Path.of(ConstantGameSettings.CONFIG_LOCATION));
        Path path = getConfigPath();

        Properties props = new Properties();
        for (Map.Entry<String, ?> entry : properties.entrySet()) {
            props.setProperty(entry.getKey(), String.valueOf(entry.getValue()));
        }

        try (OutputStream out = Files.newOutputStream(path)) {
            props.store(out, "Generated by OmniVoxel");
        }
    }
}